version: '3.4'

services:
  nginx:
    container_name: NginxCache
    restart: always
    image: nginx
    build: .
    volumes:
      - ./nginx.conf.tmpl:/etc/nginx/conf.d/variables.conf.template
    environment:
      - DOLLAR=$
      - UPSTREAM_DOMAIN=${UPSTREAM_DOMAIN}
      - UPSTREAM_PORT=${UPSTREAM_PORT}
      - UPSTREAM_HOST_HEADER=${UPSTREAM_HOST_HEADER}
      - UPSTREAM_PROTOCOL=${UPSTREAM_PROTOCOL}
      - MAX_CACHE_SIZE=${MAX_CACHE_SIZE}
      - IN_RAM_SIZE=${IN_RAM_SIZE}
      - CACHE_DURATION=${CACHE_DURATION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER}-frontend.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.${TRAEFIK_ROUTER}-frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER}-frontend.tls=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER}-frontend.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"

    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/variables.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - innernetwork

networks:
  innernetwork:
    external: true
    name: ${TRAEFIK_NETWORK}